apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: demo-voting-app-kubernetes-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: demo-voting-app-kubernetes-v1
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: demo-voting-app-kubernetes-v1
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
